fixed server crash from :
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Subaraki's Common Library (subcommonlib)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:171)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:164)
	at lib.playerclass.network.NetworkHandler.<init>(NetworkHandler.java:12)
at lib.Lib.preInit(Lib.java:26)

closes #1